USE [master]
GO

/****** Object:  Database [WorkforceMonitorDB]    Script Date: 04-12-2023 16:30:45 ******/
CREATE DATABASE [WorkforceMonitorDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WorkforceMonitorDB', FILENAME = N'G:\work app\MSSQL16.MSSQLSERVER\MSSQL\DATA\WorkforceMonitorDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'WorkforceMonitorDB_log', FILENAME = N'G:\work app\MSSQL16.MSSQLSERVER\MSSQL\DATA\WorkforceMonitorDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [WorkforceMonitorDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [WorkforceMonitorDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [WorkforceMonitorDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [WorkforceMonitorDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [WorkforceMonitorDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [WorkforceMonitorDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET RECOVERY FULL 
GO

ALTER DATABASE [WorkforceMonitorDB] SET  MULTI_USER 
GO

ALTER DATABASE [WorkforceMonitorDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [WorkforceMonitorDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [WorkforceMonitorDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [WorkforceMonitorDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [WorkforceMonitorDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [WorkforceMonitorDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [WorkforceMonitorDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [WorkforceMonitorDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [WorkforceMonitorDB] SET  READ_WRITE 
GO

