//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workforce_Monitor.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;


    public partial class TNEmpMasterTable
    {

        public int emp_id { get; set; }

        [DisplayName("Employee Code")]
        public string emp_code { get; set; }
        [DisplayName("Employee Name")]
        public string emp_name { get; set; }
        [DisplayName("Designation")]
        public string designation { get; set; }
        [DisplayName("Salary")]

        public int salary { get; set; }


    

    }
}
